CREATE TABLE users (
    id                 uuid         NOT NULL,
    created_at         timestamp    NOT NULL,
    updated_at         timestamp    NOT NULL,
    email              varchar(255) NOT NULL,
    password           varchar(255) NOT NULL,
    first_name         varchar(100) NOT NULL,
    last_name          varchar(100) NOT NULL,
    enabled            boolean      NOT NULL,
    account_non_locked boolean      NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

CREATE TABLE roles (
    id   integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name varchar(50)                              NOT NULL,
    CONSTRAINT pk_roles PRIMARY KEY (id)
);

CREATE TABLE permissions (
    id   integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name varchar(100)                             NOT NULL,
    CONSTRAINT pk_permissions PRIMARY KEY (id)
);

CREATE TABLE user_roles (
    user_id uuid    NOT NULL,
    role_id integer NOT NULL,
    CONSTRAINT pk_user_roles PRIMARY KEY (user_id, role_id)
);

CREATE TABLE role_permissions (
    role_id       integer NOT NULL,
    permission_id integer NOT NULL,
    CONSTRAINT pk_role_permissions PRIMARY KEY (role_id, permission_id)
);

CREATE TABLE token_blacklist (
    id         uuid         NOT NULL,
    jti        varchar(255) NOT NULL,
    expiration timestamp    NOT NULL,
    created_at timestamp    NOT NULL,
    CONSTRAINT pk_token_blacklist PRIMARY KEY (id)
);

ALTER TABLE users ADD CONSTRAINT uc_users_email UNIQUE (email);
ALTER TABLE roles ADD CONSTRAINT uc_roles_name UNIQUE (name);
ALTER TABLE permissions ADD CONSTRAINT uc_permissions_name UNIQUE (name);
ALTER TABLE token_blacklist ADD CONSTRAINT uc_token_blacklist_jti UNIQUE (jti);

ALTER TABLE user_roles ADD CONSTRAINT fk_userol_on_user FOREIGN KEY (user_id) REFERENCES users (id);
ALTER TABLE user_roles ADD CONSTRAINT fk_userol_on_role FOREIGN KEY (role_id) REFERENCES roles (id);
ALTER TABLE role_permissions ADD CONSTRAINT fk_rolper_on_role FOREIGN KEY (role_id) REFERENCES roles (id);
ALTER TABLE role_permissions ADD CONSTRAINT fk_rolper_on_permission FOREIGN KEY (permission_id) REFERENCES permissions (id);
