server:
  port: 4488

spring:
  application:
    name: config-server-v1
  profiles:
    active: config-server

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
