spring:
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          routes:
            - id: identity-service
              uri: lb://identity-service-v1
              predicates:
                - Path=/api/v1/auth/**, /api/v1/users/**, /api/v1/roles/**, /api/v1/permissions/**

            - id: course-service
              uri: lb://course-service-v1
              predicates:
                - Path=/api/v1/courses/**, /api/v1/sections/**, /api/v1/resources/**, /api/v1/assignments/**, /api/v1/recordings/**

            - id: enrollment-service
              uri: lb://enrollment-service-v1
              predicates:
                - Path=/api/v1/enrollments/**

            - id: learning-service
              uri: lb://learning-service-v1
              predicates:
                - Path=/api/v1/submissions/**, /api/v1/grades/**

            - id: admin-orchestrator-service
              uri: lb://admin-orchestrator-service-v1
              predicates:
                - Path=/api/v1/admin/**
