spring:
  datasource:
    url: jdbc:postgresql://localhost:41010/identitydb
    username: identityuser
    password: identitypass
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: false
